let activities = [
   {
    id: 1,
            title:"Football",
            description:"Join our 3-month football training program for children!",
            location:"Hendon, London",
            price: 30.00,
            image: "Vue.js App/images/playing 1.jpg",
            availableSpace: 15,
   },
   {
    id: 2,
    title:"Fun Maths",
    description:"Join our 2-month maths program for children!",
    location:"Colindale, London",
    price: 18.00,
    image: "Vue.js App/images/maths.jpg",
    availableSpace: 10,
   },
   {
    id: 3,
    title:"Swimming",
    description:"Join our 3-month swimming training program for children taught by 'Professionals'!",
    location:"Edgware, London",
    price: 40.00,
    image: "Vue.js App/images/swim.jpg",
    availableSpace: 10,
   },
   {
    id: 4,
    title:"Art and Paint",
    description:"Join our 4-week art and paint program for kiddos!",
    location:"Hendon, London",
    price: 10.00,
    image: "Vue.js App/images/artandpaint.jpg",
    availableSpace: 13,
   },
   {
    id: 5,
    title:"Art and Craft",
    description:"Join our 4-week art and craft program for children!",
    location:"Hendon, London",
    price: 10.00,
    image: "Vue.js App/images/artandcraft.jpg",
    availableSpace: 15,
   },
   {
    id: 6,
    title:"Fun Camp",
    description:"Join our 20-day fun camp for children which will allow the kids to learn some basic skills to be independent!",
    location:"Hendon, London",
    price: 40.00,
    image: "Vue.js App/images/fun camp.jpg",
    availableSpace: 20,
   },
   {
    id: 7,
    title:"Cycling",
    description:"Join our 1-month cycling program for children!",
    location:"Colindale, London",
    price: 12.00,
    image: "Vue.js App/images/cycling.jpg",
    availableSpace: 11,
   },
   {
    id: 8,
    title:"Coding for kids",
    description:"Let your kids get a taste of coding and programming! Join our 3-month fun coding program",
    location:"Hendon, London",
    price: 50.00,
    image: "Vue.js App/images/coding.jpg",
    availableSpace: 5,
   },
   {
    id: 9,
    title:"Baking and Cooking",
    description:"Join our 3-month Baking and Cooking training program for kids!",
    location:"Edgware, London",
    price: 40.00,
    image: "Vue.js App/images/bakingandcooking.jpg",
    availableSpace: 7,
   },
   {
    id: 10,
    title:"Music",
    description:"Let your children explore more about music and instruments! Join our 3-month music introductory program for children!",
    location:"Hendon, London",
    price: 30.00,
    image: "Vue.js App/images/music.jpg",
    availableSpace: 10,
   },
   ];
   